spring:
  application:
    name: ms-menu
  datasource:
    url: jdbc:postgresql://localhost:5432/menudb
    username: user
    password: 123456
  profiles:
    active: dev
  cloud:
    config:
      profile: dev
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
#spring.config.import=optional:configserver:http://localhost:8888